name: omnibet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.3
  video_player: ^2.2.10
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  chewie: ^1.7.5
  intl: ^0.19.0
  roulette: ^0.1.5
  provider: ^6.1.2
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/foot.mp4
    - assets/roulette.mp3
